spring:
  spring:
    jackson:
      property-naming-strategy: SNAKE_CASE
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/krud_db
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true